/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustSafetyRouteImport } from './routes/trust-safety'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BecomeProviderRouteImport } from './routes/become-provider'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as ProviderSlugRouteImport } from './routes/provider.$slug'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as DhakaAreaRouteImport } from './routes/dhaka.$area'
import { Route as BookingStatusIdRouteImport } from './routes/booking-status.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminConsoleRouteImport } from './routes/admin.console'
import { Route as AuthenticatedProviderDashboardRouteImport } from './routes/_authenticated.provider-dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated.messages'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated.invoices'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated.earnings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCoverageRouteImport } from './routes/_authenticated.coverage'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated.availability'
import { Route as ServicesCategoryIndexRouteImport } from './routes/services.$category.index'
import { Route as AdminConsoleIndexRouteImport } from './routes/admin.console.index'
import { Route as ServicesCategoryServiceRouteImport } from './routes/services.$category.$service'
import { Route as AdminConsoleProvidersRouteImport } from './routes/admin.console.providers'
import { Route as AdminConsoleOverviewRouteImport } from './routes/admin.console.overview'
import { Route as AdminConsoleFinanceRouteImport } from './routes/admin.console.finance'
import { Route as AdminConsoleCustomersRouteImport } from './routes/admin.console.customers'
import { Route as AdminConsoleContentRouteImport } from './routes/admin.console.content'
import { Route as AdminConsoleBookingsRouteImport } from './routes/admin.console.bookings'

const TrustSafetyRoute = TrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeProviderRoute = BecomeProviderRouteImport.update({
  id: '/become-provider',
  path: '/become-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSlugRoute = ProviderSlugRouteImport.update({
  id: '/provider/$slug',
  path: '/provider/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DhakaAreaRoute = DhakaAreaRouteImport.update({
  id: '/dhaka/$area',
  path: '/dhaka/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingStatusIdRoute = BookingStatusIdRouteImport.update({
  id: '/booking-status/$id',
  path: '/booking-status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedProviderDashboardRoute =
  AuthenticatedProviderDashboardRouteImport.update({
    id: '/provider-dashboard',
    path: '/provider-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoverageRoute = AuthenticatedCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ServicesCategoryIndexRoute = ServicesCategoryIndexRouteImport.update({
  id: '/services/$category/',
  path: '/services/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleIndexRoute = AdminConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConsoleRoute,
} as any)
const ServicesCategoryServiceRoute = ServicesCategoryServiceRouteImport.update({
  id: '/services/$category/$service',
  path: '/services/$category/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleProvidersRoute = AdminConsoleProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminConsoleRoute,
} as any)
const AdminConsoleOverviewRoute = AdminConsoleOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminConsoleRoute,
} as any)
const AdminConsoleFinanceRoute = AdminConsoleFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminConsoleRoute,
} as any)
const AdminConsoleCustomersRoute = AdminConsoleCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminConsoleRoute,
} as any)
const AdminConsoleContentRoute = AdminConsoleContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminConsoleRoute,
} as any)
const AdminConsoleBookingsRoute = AdminConsoleBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-provider': typeof BecomeProviderRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/coverage': typeof AuthenticatedCoverageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/provider-dashboard': typeof AuthenticatedProviderDashboardRoute
  '/admin/console': typeof AdminConsoleRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/booking-status/$id': typeof BookingStatusIdRoute
  '/dhaka/$area': typeof DhakaAreaRoute
  '/p/$id': typeof PIdRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/console/bookings': typeof AdminConsoleBookingsRoute
  '/admin/console/content': typeof AdminConsoleContentRoute
  '/admin/console/customers': typeof AdminConsoleCustomersRoute
  '/admin/console/finance': typeof AdminConsoleFinanceRoute
  '/admin/console/overview': typeof AdminConsoleOverviewRoute
  '/admin/console/providers': typeof AdminConsoleProvidersRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/admin/console/': typeof AdminConsoleIndexRoute
  '/services/$category/': typeof ServicesCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-provider': typeof BecomeProviderRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/coverage': typeof AuthenticatedCoverageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/provider-dashboard': typeof AuthenticatedProviderDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/booking-status/$id': typeof BookingStatusIdRoute
  '/dhaka/$area': typeof DhakaAreaRoute
  '/p/$id': typeof PIdRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/areas': typeof AreasIndexRoute
  '/blog': typeof BlogIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/console/bookings': typeof AdminConsoleBookingsRoute
  '/admin/console/content': typeof AdminConsoleContentRoute
  '/admin/console/customers': typeof AdminConsoleCustomersRoute
  '/admin/console/finance': typeof AdminConsoleFinanceRoute
  '/admin/console/overview': typeof AdminConsoleOverviewRoute
  '/admin/console/providers': typeof AdminConsoleProvidersRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/admin/console': typeof AdminConsoleIndexRoute
  '/services/$category': typeof ServicesCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-provider': typeof BecomeProviderRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/coverage': typeof AuthenticatedCoverageRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/provider-dashboard': typeof AuthenticatedProviderDashboardRoute
  '/admin/console': typeof AdminConsoleRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/booking-status/$id': typeof BookingStatusIdRoute
  '/dhaka/$area': typeof DhakaAreaRoute
  '/p/$id': typeof PIdRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/console/bookings': typeof AdminConsoleBookingsRoute
  '/admin/console/content': typeof AdminConsoleContentRoute
  '/admin/console/customers': typeof AdminConsoleCustomersRoute
  '/admin/console/finance': typeof AdminConsoleFinanceRoute
  '/admin/console/overview': typeof AdminConsoleOverviewRoute
  '/admin/console/providers': typeof AdminConsoleProvidersRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/admin/console/': typeof AdminConsoleIndexRoute
  '/services/$category/': typeof ServicesCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/become-provider'
    | '/book'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-safety'
    | '/availability'
    | '/coverage'
    | '/dashboard'
    | '/earnings'
    | '/invoices'
    | '/messages'
    | '/profile'
    | '/provider-dashboard'
    | '/admin/console'
    | '/blog/$slug'
    | '/booking-status/$id'
    | '/dhaka/$area'
    | '/p/$id'
    | '/provider/$slug'
    | '/areas/'
    | '/blog/'
    | '/providers/'
    | '/services/'
    | '/admin/console/bookings'
    | '/admin/console/content'
    | '/admin/console/customers'
    | '/admin/console/finance'
    | '/admin/console/overview'
    | '/admin/console/providers'
    | '/services/$category/$service'
    | '/admin/console/'
    | '/services/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/become-provider'
    | '/book'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-safety'
    | '/availability'
    | '/coverage'
    | '/dashboard'
    | '/earnings'
    | '/invoices'
    | '/messages'
    | '/profile'
    | '/provider-dashboard'
    | '/blog/$slug'
    | '/booking-status/$id'
    | '/dhaka/$area'
    | '/p/$id'
    | '/provider/$slug'
    | '/areas'
    | '/blog'
    | '/providers'
    | '/services'
    | '/admin/console/bookings'
    | '/admin/console/content'
    | '/admin/console/customers'
    | '/admin/console/finance'
    | '/admin/console/overview'
    | '/admin/console/providers'
    | '/services/$category/$service'
    | '/admin/console'
    | '/services/$category'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/become-provider'
    | '/book'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-safety'
    | '/_authenticated/availability'
    | '/_authenticated/coverage'
    | '/_authenticated/dashboard'
    | '/_authenticated/earnings'
    | '/_authenticated/invoices'
    | '/_authenticated/messages'
    | '/_authenticated/profile'
    | '/_authenticated/provider-dashboard'
    | '/admin/console'
    | '/blog/$slug'
    | '/booking-status/$id'
    | '/dhaka/$area'
    | '/p/$id'
    | '/provider/$slug'
    | '/areas/'
    | '/blog/'
    | '/providers/'
    | '/services/'
    | '/admin/console/bookings'
    | '/admin/console/content'
    | '/admin/console/customers'
    | '/admin/console/finance'
    | '/admin/console/overview'
    | '/admin/console/providers'
    | '/services/$category/$service'
    | '/admin/console/'
    | '/services/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomeProviderRoute: typeof BecomeProviderRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustSafetyRoute: typeof TrustSafetyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BookingStatusIdRoute: typeof BookingStatusIdRoute
  DhakaAreaRoute: typeof DhakaAreaRoute
  PIdRoute: typeof PIdRoute
  ProviderSlugRoute: typeof ProviderSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesCategoryServiceRoute: typeof ServicesCategoryServiceRoute
  ServicesCategoryIndexRoute: typeof ServicesCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-safety': {
      id: '/trust-safety'
      path: '/trust-safety'
      fullPath: '/trust-safety'
      preLoaderRoute: typeof TrustSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-provider': {
      id: '/become-provider'
      path: '/become-provider'
      fullPath: '/become-provider'
      preLoaderRoute: typeof BecomeProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$slug': {
      id: '/provider/$slug'
      path: '/provider/$slug'
      fullPath: '/provider/$slug'
      preLoaderRoute: typeof ProviderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhaka/$area': {
      id: '/dhaka/$area'
      path: '/dhaka/$area'
      fullPath: '/dhaka/$area'
      preLoaderRoute: typeof DhakaAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-status/$id': {
      id: '/booking-status/$id'
      path: '/booking-status/$id'
      fullPath: '/booking-status/$id'
      preLoaderRoute: typeof BookingStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console': {
      id: '/admin/console'
      path: '/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/provider-dashboard': {
      id: '/_authenticated/provider-dashboard'
      path: '/provider-dashboard'
      fullPath: '/provider-dashboard'
      preLoaderRoute: typeof AuthenticatedProviderDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coverage': {
      id: '/_authenticated/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof AuthenticatedCoverageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/services/$category/': {
      id: '/services/$category/'
      path: '/services/$category'
      fullPath: '/services/$category/'
      preLoaderRoute: typeof ServicesCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console/': {
      id: '/admin/console/'
      path: '/'
      fullPath: '/admin/console/'
      preLoaderRoute: typeof AdminConsoleIndexRouteImport
      parentRoute: typeof AdminConsoleRoute
    }
    '/services/$category/$service': {
      id: '/services/$category/$service'
      path: '/services/$category/$service'
      fullPath: '/services/$category/$service'
      preLoaderRoute: typeof ServicesCategoryServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console/providers': {
      id: '/admin/console/providers'
      path: '/providers'
      fullPath: '/admin/console/providers'
      preLoaderRoute: typeof AdminConsoleProvidersRouteImport
      parentRoute: typeof AdminConsoleRoute
    }
    '/admin/console/overview': {
      id: '/admin/console/overview'
      path: '/overview'
      fullPath: '/admin/console/overview'
      preLoaderRoute: typeof AdminConsoleOverviewRouteImport
      parentRoute: typeof AdminConsoleRoute
    }
    '/admin/console/finance': {
      id: '/admin/console/finance'
      path: '/finance'
      fullPath: '/admin/console/finance'
      preLoaderRoute: typeof AdminConsoleFinanceRouteImport
      parentRoute: typeof AdminConsoleRoute
    }
    '/admin/console/customers': {
      id: '/admin/console/customers'
      path: '/customers'
      fullPath: '/admin/console/customers'
      preLoaderRoute: typeof AdminConsoleCustomersRouteImport
      parentRoute: typeof AdminConsoleRoute
    }
    '/admin/console/content': {
      id: '/admin/console/content'
      path: '/content'
      fullPath: '/admin/console/content'
      preLoaderRoute: typeof AdminConsoleContentRouteImport
      parentRoute: typeof AdminConsoleRoute
    }
    '/admin/console/bookings': {
      id: '/admin/console/bookings'
      path: '/bookings'
      fullPath: '/admin/console/bookings'
      preLoaderRoute: typeof AdminConsoleBookingsRouteImport
      parentRoute: typeof AdminConsoleRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedCoverageRoute: typeof AuthenticatedCoverageRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProviderDashboardRoute: typeof AuthenticatedProviderDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedCoverageRoute: AuthenticatedCoverageRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProviderDashboardRoute: AuthenticatedProviderDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminConsoleRouteChildren {
  AdminConsoleBookingsRoute: typeof AdminConsoleBookingsRoute
  AdminConsoleContentRoute: typeof AdminConsoleContentRoute
  AdminConsoleCustomersRoute: typeof AdminConsoleCustomersRoute
  AdminConsoleFinanceRoute: typeof AdminConsoleFinanceRoute
  AdminConsoleOverviewRoute: typeof AdminConsoleOverviewRoute
  AdminConsoleProvidersRoute: typeof AdminConsoleProvidersRoute
  AdminConsoleIndexRoute: typeof AdminConsoleIndexRoute
}

const AdminConsoleRouteChildren: AdminConsoleRouteChildren = {
  AdminConsoleBookingsRoute: AdminConsoleBookingsRoute,
  AdminConsoleContentRoute: AdminConsoleContentRoute,
  AdminConsoleCustomersRoute: AdminConsoleCustomersRoute,
  AdminConsoleFinanceRoute: AdminConsoleFinanceRoute,
  AdminConsoleOverviewRoute: AdminConsoleOverviewRoute,
  AdminConsoleProvidersRoute: AdminConsoleProvidersRoute,
  AdminConsoleIndexRoute: AdminConsoleIndexRoute,
}

const AdminConsoleRouteWithChildren = AdminConsoleRoute._addFileChildren(
  AdminConsoleRouteChildren,
)

interface AdminRouteChildren {
  AdminConsoleRoute: typeof AdminConsoleRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConsoleRoute: AdminConsoleRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeProviderRoute: BecomeProviderRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustSafetyRoute: TrustSafetyRoute,
  BlogSlugRoute: BlogSlugRoute,
  BookingStatusIdRoute: BookingStatusIdRoute,
  DhakaAreaRoute: DhakaAreaRoute,
  PIdRoute: PIdRoute,
  ProviderSlugRoute: ProviderSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesCategoryServiceRoute: ServicesCategoryServiceRoute,
  ServicesCategoryIndexRoute: ServicesCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
